### ISSUE TITLE
When compiling to iOS, wwise creates a .framework with an underscore ('_') which is not supported

### ISSUE THREAD

**Issue by brantkings** [alessandrofama/wwise-godot-integration#101]
### Wwise integration version

Wwise 2023.1 for Godot 4.2 v2.0.4

### System information

MacOSX Big Sur 11.4

### Issue description

When you export to iOS, in XCODE it adds a .framework called libwwise.ios.template_debug.framework. When uploading to the app store, it says the _ is illegal which causes an error:

![Screen Shot 2024-09-06 at 15 53 09](https://github.com/user-attachments/assets/949397fc-ef20-421c-b1bb-745667fd7caa)

Exporting with release won't solve it, as it will just do '_release' instead of '_debug'.

Yes I also believe Apple is super annoying 😢

### Steps to reproduce

Just export to iOS.

### Minimal reproduction project

Any empty godot project with wwise will cause it I suppose.

**Comment by brantkings** [comment]
Thanks!

**Comment by brantkings** [comment]
Found a quick fix for this, in case @alessandrofama or somebody else needs:

In the exported xcode project, the problem is just the CFBundleIdentifier from the library. You can right-click (or command-click it), open it in Finder and change the CFBundleIdentifier in the .plist inside it! The library itself will not request this bundle identifier so you're good to go!

![Screen Shot 2024-09-06 at 15 53 10 1](https://github.com/user-attachments/assets/f3c3e608-555c-4919-a173-b43db99636cd)

**Comment by alessandrofama** [comment]
The CFBundleIdentifier for the libraries should be generated here during compilation with scons: https://github.com/alessandrofama/wwise-godot-integration/blob/542beb0c8315c69e63723c1443ce80f0e19bd42f/addons/Wwise/native/SConstruct#L409
Should be an easy change making sure it doesn’t include the _.
