### ISSUE TITLE
Error Loading Bank IDs?

### ISSUE THREAD

**Issue by smks** [alessandrofama/wwise-godot-integration#12]
I have managed to generate the soundbanks and export the header ID to map to the Banks & Events, but getting the following errors to load the Bank. Also looks like I can see a full path to the author's CPP files.

Wwise version: 2019.2.1.7250

```
class_name AK

class EVENTS:
    const FOOTSTEP = 1044567165
    const MUSIC = 3991942870

    enum _enum {
        FOOTSTEP = 1044567165,
        MUSIC = 3991942870
    }

class GAME_PARAMETERS:
    const DENSITY_FA_SSGRAIN = 2715217995
    const IMMERSION_FA_SSGRAIN = 2481728872
    const INSTRUMENT_FA_SSGRAIN = 2317409760
    const PLAYBACK_RATE = 1524500807
    const PROXIMITY_FA_SSGRAIN = 1791284502
    const RPM = 796049864
    const RPM_FA_SSGRAIN = 1656280998
    const SIMULATION_FA_SSGRAIN = 2428833394
    const SOIL_RTPC = 731927630
    const SS_AIR_FEAR = 1351367891
    const SS_AIR_FREEFALL = 3002758120
    const SS_AIR_FURY = 1029930033
    const SS_AIR_MONTH = 2648548617
    const SS_AIR_PRESENCE = 3847924954
    const SS_AIR_RPM = 822163944
    const SS_AIR_SIZE = 3074696722
    const SS_AIR_STORM = 3715662592
    const SS_AIR_TIMEOFDAY = 3203397129
    const SS_AIR_TURBULENCE = 4160247818

    enum _enum {
        DENSITY_FA_SSGRAIN = 2715217995,
        IMMERSION_FA_SSGRAIN = 2481728872,
        INSTRUMENT_FA_SSGRAIN = 2317409760,
        PLAYBACK_RATE = 1524500807,
        PROXIMITY_FA_SSGRAIN = 1791284502,
        RPM = 796049864,
        RPM_FA_SSGRAIN = 1656280998,
        SIMULATION_FA_SSGRAIN = 2428833394,
        SOIL_RTPC = 731927630,
        SS_AIR_FEAR = 1351367891,
        SS_AIR_FREEFALL = 3002758120,
        SS_AIR_FURY = 1029930033,
        SS_AIR_MONTH = 2648548617,
        SS_AIR_PRESENCE = 3847924954,
        SS_AIR_RPM = 822163944,
        SS_AIR_SIZE = 3074696722,
        SS_AIR_STORM = 3715662592,
        SS_AIR_TIMEOFDAY = 3203397129,
        SS_AIR_TURBULENCE = 4160247818
    }

class BANKS:
    const INIT = 1355168291
    const ACT0 = 3504395757

    enum _enum {
        INIT = 1355168291,
        ACT0 = 3504395757
    }

class BUSSES:
    const MASTER_AUDIO_BUS = 3803692087
    const MOTION_FACTORY_BUS = 985987111

    enum _enum {
        MASTER_AUDIO_BUS = 3803692087,
        MOTION_FACTORY_BUS = 985987111
    }

class AUDIO_DEVICES:
    const DEFAULT_MOTION_DEVICE = 4230635974
    const NO_OUTPUT = 2317455096
    const SYSTEM = 3859886410

    enum _enum {
        DEFAULT_MOTION_DEVICE = 4230635974,
        NO_OUTPUT = 2317455096,
        SYSTEM = 3859886410
    }
class AUX_BUSSES:
     enum _enum {}

```

![image](https://user-images.githubusercontent.com/4087157/100542472-f7684180-3241-11eb-82cb-28cf32495dcf.png)

![image](https://user-images.githubusercontent.com/4087157/100542528-529a3400-3242-11eb-8524-cb38cf141ce0.png)

**Comment by alessandrofama** [comment]
Hi! 
Can you try to load the Init Bank first and Act 0 later? That should fix it. Make sure the Init bank is actually selected (it's an issue: https://github.com/alessandrofama/wwise-godot-integration/issues/4).

**Comment by smks** [comment]
namespace BANKS
    {
        static const AkUniqueID INIT = 1355168291U;
        static const AkUniqueID ACT0 = 3504395757U;
    } // namespace BANKS

I see the header has a U suffix?

**Comment by smks** [comment]
Init Bank loaded without ACT0 - same issue 👍 
![image](https://user-images.githubusercontent.com/4087157/100542756-f46e5080-3243-11eb-9f8b-417f638dff59.png)

**Comment by smks** [comment]
Selected it too to ensure the ID was being fed through.

**Comment by alessandrofama** [comment]
Can you please check that the `Use SoundBank names` checkbox is deselected in the Wwise project settings? It's not possible to use Wwise ID's if that is not the case.

**Comment by smks** [comment]
That was the problem, thank you so much! 💯 🥇 

Monitor is throwing a few issues but got the music event firing now!!

![image](https://user-images.githubusercontent.com/4087157/100543215-b7f02400-3246-11eb-88db-0de43f655175.png)

**Comment by alessandrofama** [comment]
Both errors are related to a missing plugin, the plug-in id suggests it's the [Wwise Motion](https://www.audiokinetic.com/products/plug-ins/motion/) plugin. If you are not using it I would suggest to remove it from Wwise Authoring (should appear in Wwise Launcher -> Plugins) and then from your project. If you want to use that plugin it is necessary to recompile the integration.

Good to hear you solved that banks issue. I will update the Wiki to make more clear Wwise Id's can't be used when using SoundBank names. 
I will close this issue but please feel free to open new issues for other problems. It helps to improve this library and fix some overlooked errors. 
Cheers!

**Comment by smks** [comment]
Thank you again, very kind of you and prompt

**Comment by RileyCircles** [comment]
I am having this exact same issue except I have had Use Soundbank Names for Filenames unchecked since the start (my Project Settings look slightly different but I believe that is the equivalent of Use Soundbank Names) and it is still not loading. 

Wwise version: 2022.1.0.7985 
Godot 3.5

**Comment by alessandrofama** [comment]
@RileyCircles 

We don't support Wwise version 2022 as it's in beta. There might be significant API changes in Wwise that make newer banks incompatible for lower sound engine versions, see https://www.audiokinetic.com/library/edge/?source=Help&id=soundbank_backward_compatibility  I would suggest you downgrade to the version listed in the readme of this repo or wait until I add support for 2022.
