### ISSUE TITLE
Unable to Locate Generated Soundbanks within Godot

### ISSUE THREAD

**Issue by oscarito-423** [alessandrofama/wwise-godot-integration#15]
Generated soundbanks were created but Godot does not recognize any files within the folder. Init file is also not visible within godot.

AkBank -Bank- input is empty.

-----I'm an idiot------
*Forgot to convert Wwise ID's.

**Comment by alessandrofama** [comment]
Hi Oscar, did you manage to get Godot to recognize the banks by converting the ID's? Did it work out?

**Comment by oscarito-423** [comment]
Alessandro I got it working, thank you!
Amazing job! Not an experienced coder so getting this integration going is definitely helpful!

**Comment by alessandrofama** [comment]
You're welcome! Feel free to open other issues for other problems. Cheers
