### ISSUE TITLE
Empty Dropdown list, but have generated the wwise IDs. Any ideas?

### ISSUE THREAD

**Issue by smks** [alessandrofama/wwise-godot-integration#18]
![Screenshot 2021-01-16 at 16 40 04](https://user-images.githubusercontent.com/4087157/104817497-85f84880-5819-11eb-9d6b-89f7180fe180.png)

![Screenshot 2021-01-16 at 16 41 03](https://user-images.githubusercontent.com/4087157/104817518-a6280780-5819-11eb-8557-0588b1014e69.png)

**Comment by alessandrofama** [comment]
Hi! 

Could you try restarting the Godot Editor? It seems like Godot has a problem updating these values. It usually works for me if I restart the editor after generating the id's.

**Comment by alessandrofama** [comment]
Did it work out for you? I'm closing this and created a more general issue since it doesn't affect only banks: https://github.com/alessandrofama/wwise-godot-integration/issues/20

Please write there if the proposed workaround doesn't work for you.
