### ISSUE TITLE
Cannot click on Font Data inner resource after integrating with wwise

### ISSUE THREAD

**Issue by jontopielski** [alessandrofama/wwise-godot-integration#25]
![Screen Shot 2021-03-02 at 8 18 51 PM](https://user-images.githubusercontent.com/6269590/109752115-a9dad800-7b94-11eb-9e93-0992712dca82.png)

After integrating with wwise, when I create a new DynamicFontData and then create a DynamicFontData, I can't click the new DynamicFontData in order to edit it. Wondering if this might have something to do with the way wwise applies custom nodes / resources to the project. Help would be appreciated, thanks!

**Comment by alessandrofama** [comment]
Hi Jon, 

thanks for the report. I can't reproduce the issue. Could you share more details about your setup and project?

- What exact Godot version and OS are you using?
- Do you get any errors or warning at all?
- Does the problem occur on a new project without Wwise integrated?
- Does it only occur after you have integrated Wwise?
- If the problem occurs only on a project with Wwise integrated, can you share a minimal reproduction project?

**Comment by jontopielski** [comment]
> * What exact Godot version and OS are you using?

- Godot Engine 3.2.stable.official
- Mac OS Catalina 10.15.6

> * Do you get any errors or warning at all?

Nope
> * Does the problem occur on a new project without Wwise integrated?

No. Here is what it looks like before wwise integration:
![edit_font_works](https://user-images.githubusercontent.com/6269590/109923025-12988200-7c73-11eb-89ff-bd13129997d4.gif)

> * Does it only occur after you have integrated Wwise?

Yes, here are the steps I went through.
<img width="696" alt="Screen Shot 2021-03-03 at 10 53 43 PM" src="https://user-images.githubusercontent.com/6269590/109923229-5095a600-7c73-11eb-9303-af095982ae48.png">

After installing, here is what trying to edit FontData looks like:
![edit_font_not_working](https://user-images.githubusercontent.com/6269590/109923493-b97d1e00-7c73-11eb-9dfe-5b81d4852fe2.gif)


> * If the problem occurs only on a project with Wwise integrated, can you share a minimal reproduction project?

https://github.com/jontopielski/wwise-debug (note: did not include the binaries in wwise/bin)

Thank you for taking a look!

**Comment by alessandrofama** [comment]
Thank you for the details, much appreciated. Well...that is a weird problem 🤔. I will look into it and come back to you.

**Comment by alessandrofama** [comment]
Seems like this is the result of a mistake I made in the waapi-picker addon. It doesn't affect only these font fields, but all "nested" properties.

In ``waapi_picker.gd``, replace:

```
func handles(object):
    return true 
```

with:

```
func handles(object):
    return object.get_class() == "Spatial"
```

Restart the editor after that.

This fix will be added to the next release.

**Comment by jontopielski** [comment]
@alessandrofama thank you!
