### ISSUE TITLE
Invalid type in function 'distance_to' in base 'Vector2'.

### ISSUE THREAD

**Issue by MrdoodSFX** [alessandrofama/wwise-godot-integration#27]
After i followed the instructions on all the youtube vidéos you've made i got this error in the console :

res://addons/waapi_picker/waapi_picker.gd:405 - Invalid type in function 'distance_to' in base 'Vector2'. Cannot convert argument 1 from Vector3 to Vector2.

And when I try to create any "ak" the windows looks like this 

![Capture2](https://user-images.githubusercontent.com/61285322/114473682-fc2c0180-9bf4-11eb-8a77-1957cc272d7c.JPG)

Im on windows btw,

Thx !

**Comment by alessandrofama** [comment]
Hi @MrdoodSFX,
thanks for sharing this problem. I've never experienced this, so do you have a project you can share with me that has this issue, so I can take a closer look? Which Godot version are you using by the way?

**Comment by MrdoodSFX** [comment]
Thanks for you're answer, first i wanna precise that I'm not a dev but a sound designer. I m working on godot 3.2.3, and wwise 
2019.2.1.7250. How can i share you the project ?

**Comment by alessandrofama** [comment]
That's not a problem. You can .zip it (do you know how?) and upload it on [WeTransfer](https://wetransfer.com/) for example. Send the resulting link privately via e-mail (me@alessandrofama.com) or post it here :)

**Comment by MrdoodSFX** [comment]
Ok it's send !

**Comment by alessandrofama** [comment]
The problem here was that the Root node was a Control node and not a Spatial node. The Waapi Picker needs a Spatial node to be able to place Wwise Objects as Events in the Viewport. Fixed by https://github.com/alessandrofama/wwise-godot-integration/commit/bbe4b6eeb4e7a64c265f993f12a793daf5fd9ff2 .
