### ISSUE TITLE
Failed test of empty scene after running integration app

### ISSUE THREAD

**Issue by ChrisWhatever1980** [alessandrofama/wwise-godot-integration#29]
I followed the instructions from the video **Installation - Wwise Godot Integration**: https://www.youtube.com/watch?v=Z2Rs81P1iic

When testing the empty scene after running the integration app these errors are produced:
(I have a german system, Last part of the first message says: Module not found)

```
E 0:00:00.612   open_dynamic_library: Can't open dynamic library: D:/Projects/Godot/WwiseTest/wwise/bin/win64/debug/WwiseGDNative.dll, error: Error 126: Das angegebene Modul 

wurde nicht gefunden.
  <C++ Error>   Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <C++ Source>  platform/windows/os_windows.cpp:2395 @ open_dynamic_library()

E 0:00:00.616   get_symbol: No valid library handle, can't get symbol from GDNative object
  <C++ Source>  modules/gdnative/gdnative.cpp:501 @ get_symbol()

E 0:00:00.620   init_library: No nativescript_init in "res://wwise/bin/win64/debug/WwiseGDNative.dll" found
  <C++ Source>  modules/gdnative/nativescript/nativescript.cpp:1506 @ init_library()

E 0:00:00.623   start: Script does not inherit a Node: res://wwise/bin/wwise-gdnative-debug.gdns
  <C++ Error>   Condition "!valid_type" is true. Continuing.
  <C++ Source>  main/main.cpp:1766 @ start()
```

The autoloads as well as the plugins have loaded and are active. The node types are present as well. The output message _wwise system intialisation succeeded_ does **not** appear.

Steps to reproduce:
Godot Engine v3.2.3.stable.official
Zipped project for reproducing: https://drive.google.com/file/d/1FYYNPg-vJ9dX3K5yOZMCmv5uy6LZ31OY/view?usp=sharing
Open project in Godot and play.

**Comment by alessandrofama** [comment]
Hi Chris,

Haven't looked at the project yet, but usually this error on Windows is related to missing debug versions of the Visual C++ runtime DLLs on your system. You can open our Wwise .dll with a dependency walker (https://lucasg.github.io/Dependencies/) and check if something is missing.

In that case could you verify that you have the MSVC C++-x64/x86-Buildtools installed? You can find them as a package in the Visual Studio Installer. For example the `MSVC v142 - VS 2019 C++ Build Tools`. Installing these usually resolves the error.

**Comment by ChrisWhatever1980** [comment]
yeah, that did it, thank you very much!
