### ISSUE TITLE
"Device ShareSet not found in Init bank" when playing scene with AKBank node

### ISSUE THREAD

**Issue by ChrisWhatever1980** [alessandrofama/wwise-godot-integration#30]
When playing a scene that contains an AKBank node loading the Init bank an error message says **Device ShareSet not found in Init**.

```
E 0:00:01.091   Wwise monitor: AK::SoundEngine::AddOutput()/ReplaceOutput() - Device ShareSet not found in Init bank.
  <C++ Source>  :0 @ Wwise monitor()
```

Is this something I have to add in the wwise authoring environment?
I tried following Lesson 1 from the wwise documentation using the downloaded Lession 1 project as a base. I also tried a project from scratch.

Full disclosure: I am not an audio engineer and have not worked with wwise before.

Wwise:   2019.2.1 Build 7250
Godot:   v3.3.stable.official

**Comment by alessandrofama** [comment]
Check if the `Audio Device Shareset` name in the Godot Project Settings (highlighted here in the first screenshot) is the same as your Wwise Audio device, which usually should be `System`. Both having the same name should resolve this error. 
![image](https://user-images.githubusercontent.com/26153311/116306285-2a890f80-a7a5-11eb-9964-71e52ff066ef.png)
![image](https://user-images.githubusercontent.com/26153311/116306323-35dc3b00-a7a5-11eb-87fc-9d0fe1a4b184.png)

**Comment by ChrisWhatever1980** [comment]
Thanks that was it, the Audio Device Shareset in Godot was empty.

**Comment by alessandrofama** [comment]
I will check if it's empty by default and fix this in that case. Thanks for confirming this was the problem!
