### ISSUE TITLE
Request/Wish for samples with matching wwise and Godot projects

### ISSUE THREAD

**Issue by ChrisWhatever1980** [alessandrofama/wwise-godot-integration#31]
I would love to take a look at a example of a wwise project and a matching Godot project.
PS: Or is there one and I couldn't find it...

**Comment by alessandrofama** [comment]
You can find a Godot demo project with some demo scenes in this repository under `wwise-gdnative/gdnative-demo`. The corresponding Wwise project is in the same directory, named `gdnative-demo-wwise-project`.

**Comment by ChrisWhatever1980** [comment]
Thanks!
