### ISSUE TITLE
Failed to load plugin then corrupted Godot project

### ISSUE THREAD

**Issue by nicolasGab** [alessandrofama/wwise-godot-integration#33]
Hi there, I'm trying out the Wwise integration for Godot. I followed the instructions, used the integration app on my Godot project, and I haven't managed to get it to work.  
## Step 1 
With my Godot project open in the Godot editor, I ran the integration app, reloaded the godot.project file once prompted to do so, and went to the project settings to enable the plugins. When ticking the boxes, I got an error telling me the files could not be opened. Upon inspection, the files in the "wwise" folder were throwing the following error:

```
The identifier "Wwise" isn't declared in the current scope
```

I tried doing this a few times and it did not change anything.  
## Step 2
I closed my Godot project and ran the integration app once more. When I tried reopening my Godot project, I got the following error: 

```
The following project settings file does not specify the version of Godot through which it was created.
[...]
If you proceed with opening it, it will be converted to Godot's current configuration file format.
[...] 
```

I clicked "ok" after this message and the project did not load. It tried to launch then fell back to the Godot project list.

I'm posting this issue because it might be very frustrating for people who do not use Git or who do not have a backup of their project.

__________
Godot version: 3.3 MONO
System version: MacOS 10.15.4

**Comment by nicolasGab** [comment]
I used the latest release `1.1.0_Wwise2019.2.1.7250` (which, of course, specifies the compatibility to Godot 3.2.x only)

**Comment by alessandrofama** [comment]
Try to install the integration while Godot is closed. Godot doesn't update properly when the project.godot file gets updated while the engine is opened. Alternatively, you need to add the following scripts manually to the AutoLoad tab of the project settings and enable the plugins after that:

![image](https://user-images.githubusercontent.com/26153311/124278017-056aa180-db46-11eb-8fa8-21716ffea699.png)

Having a project corrupted can happen in this release, as we are parsing and updating the project.godot file. Something messed up that file when you tried to install the integration for a second time. But we moved away from this method now and should not happen in the next release. 

If you still get a corrupted project please try to install the integration manually by following these steps:

1) Download the integration.zip archive and extract it to your Godot project.
2) Download your desired platform.zip archive and extract it to `godot-project/wwise/bin`.
3) Add the AutoLoad scripts manually as showed in the image above.
4) Enable the plugins.

> I'm posting this issue because it might be very frustrating for people who do not use Git or who do not have a backup of their project.

Copy the project.godot file from an empty project to the corrupted project. This should fix the loading issue. Obviously I would recommend to always backup your projects or to use version control.

**Comment by alessandrofama** [comment]
Should be fixed in the latest release. https://github.com/alessandrofama/wwise-godot-integration/releases/tag/1.2.0_Wwise2019.2.1.7250
