### ISSUE TITLE
Playback during focus loss

### ISSUE THREAD

**Issue by stacyh3** [alessandrofama/wwise-godot-integration#35]
Is there a way to continue Wwise playback during focus loss? This is a pretty important feature for an app that we're looking to develop with Godot.

**Comment by alessandrofama** [comment]
Yep, this is handled here: 

https://github.com/alessandrofama/wwise-godot-integration/blob/4465ab157c95c6d51ecc7bfc231884f4c4200305/wwise-gdnative/src/wwise_gdnative.cpp#L227-L239

It's hardcoded right now, but ideally this should be an option in the project settings. You can comment out the code inside that function and rebuild the binaries. If I manage to have some time soon I can fix this directly.

**Comment by alessandrofama** [comment]
Libs to replace:
[Android](https://github.com/alessandrofama/wwise-godot-integration/suites/3504733144/artifacts/83538311)
[iOS](https://github.com/alessandrofama/wwise-godot-integration/suites/3504733154/artifacts/83539395)
[macOS](https://github.com/alessandrofama/wwise-godot-integration/suites/3504733143/artifacts/83538368)
[Windows](https://github.com/alessandrofama/wwise-godot-integration/suites/3504733140/artifacts/83538144)
[Linux](https://github.com/alessandrofama/wwise-godot-integration/suites/3504733139/artifacts/83538089)

Replace this file in the ``wwise`` folder: https://raw.githubusercontent.com/alessandrofama/wwise-godot-integration/main/wwise-gdnative/gdnative-demo/wwise/wwise_settings.gd

and disable this setting in the project settings (Wwise - Common User Settings): 
![image](https://user-images.githubusercontent.com/26153311/129490758-3966cd27-c4d8-4549-a6ce-63fdfe21ec9c.png)

**Comment by stacyh3** [comment]
I gave this a quick try on an Android device. I'm a long time developer, but new to Android and Godot, so there may be something else needed. When I go to the phone's home screen, playback stops. When I switch back to the app, playback starts again.

**Comment by alessandrofama** [comment]
Works on desktop, I will try it on my Android device later today! Not super experienced in working with mobile.. there might be some setting that keeps the app alive.

**Comment by alessandrofama** [comment]
I've tried this out on an old Xiaomi Redmi Note 3 (Android 7.0) and switching to the home screen or locking while audio is playing works fine. Maybe newer or specific Android versions behave more strict? Wwise docs don't say anything specific about Android: https://www.audiokinetic.com/library/2019.2.12_7544/?source=SDK&id=workingwithsdks_system_calls.html

If you applied the changes above it should work fine. If you manage to find time for a simple repro project I can take another look at this.

**Comment by stacyh3** [comment]
I'll try for a repro project. I may have goofed up on the settings. Should I close this for now or leave it going until I can test. It might be a few days.

**Comment by alessandrofama** [comment]
You can leave this issue opened, does not bother me at all.

**Comment by stacyh3** [comment]
Thanks. I'm testing between other things at work. I went back to a simple empty Godot project and I can build and deploy it. When I add in the Wwise features I'm getting a apksigner error. I'll try to track this down and get a working test.

**Comment by stacyh3** [comment]
Success! I started with an empty app and checked the export at each step. Working great! Thanks! You are fantastic! Now I'm thinking about doing a similar type of integration project for Xamarin/MAUI apps. Hmm... Thanks again!
