### ISSUE TITLE
Wwise version support plans

### ISSUE THREAD

**Issue by honix** [alessandrofama/wwise-godot-integration#36]
Hello! Really glad to see projects growing around Godot's ecosystem.

I'm looking for audio engine to use with Godot and I have a question:

Readme tells "Wwise version 2019.2.1.7250 is supported" is this strictly locks to this version of wwise or it's tested only version? If it locks, what is needed to push it to wwise latest version or do you plan to push it?

Thanks!

**Comment by alessandrofama** [comment]
You can find some rough steps to update the Wwise version here: https://github.com/alessandrofama/wwise-godot-integration/wiki/Wwise-version-upgrade

Our libs should work with every 2019.2.x version, as minor updates do not break compatibility as detailed here: https://www.audiokinetic.com/library/edge/?source=InstallGuide&id=wwise_versioning

The 2021 is a new major version, so I would expect breaking API changes. 

To update to the latest Wwise version I would download the latest SDK and try to build the wwise-gdnative and waapiclient-gdnative wrappers. You'll encounter some build errors that should be fixable with some minor work. 

I do plan to update this integration to the latest 2021 version but I can't give you an exact time frame right now. Next month would be great!

**Comment by honix** [comment]
Thanks for a detailed answer!

I think 2019.2.1.7250 is okay for my project for now, but this will be great to have latest wwise too if possible! Maybe I will try to rebuild wrappers as you mention.

Really I think the changes between wwise versions is really little, overall its the same feature set. It is more mental issue with older version, it seems obsolete, but it's usable anyway.

Thanks your and team for the work!

**Comment by stacyh3** [comment]
I'm new to Wwise, but I was able to get this working with the latest Wwise build - although but not in the best way. There were a few APIs that I commented out until I can figure out how to update the code for them. I also found that due to the header file AkOpusDecoderFactory.h, I had to add a library - AkOpusDecoder - to the build. I followed the instruction that @alessandrofama has on YouTube and was able to fill in the missing bits. I think AudioKinetic should fund keeping this integration up to date. Godot is growing quite a bit and this is a great way to get sound designers into the mix.

**Comment by alessandrofama** [comment]
I think I will update to 2021 after my vacation next week. Glad you managed to do that on your own 👍  What API did you have to comment out? Spatial Audio?

**Comment by stacyh3** [comment]
Sorry I missed your question. Yes, it was code related to Spatial Audio that I had to comment out. I hope all is well!

**Comment by alessandrofama** [comment]
Working on it right now, created a new branch for the update.

**Comment by smks** [comment]
Will be awesome to use 2021 :D

**Comment by alessandrofama** [comment]
support for 2021 was added in https://github.com/alessandrofama/wwise-godot-integration/pull/40
