### ISSUE TITLE
WIki on Adding Unit tests

### ISSUE THREAD

**Issue by smks** [alessandrofama/wwise-godot-integration#37]
Hey just wondering if there are any docs on how to use this library's unit testing capabilities?

Integrated unit testing with GUT and my run does things like this. This is running in an ubuntu-latest agent with a godot-ci docker image on Github via Actions.

```
SCRIPT ERROR: register_game_object: Invalid call. Nonexistent function 'register_game_obj' in base 'Nil'.
* test_main
   At: res://wwise/runtime/nodes/ak_event_2d.gd:56.
SCRIPT ERROR: post_event: Invalid call. Nonexistent function 'post_event_id' in base 'Nil'.
   At: res://wwise/runtime/nodes/ak_event_2d.gd:22.
SCRIPT ERROR: _play: Invalid call. Nonexistent function 'post_event_id' in base 'Nil'.
```

**Comment by alessandrofama** [comment]
Mmmh no docs but we used GUT in the demo project in this repo. Can you post the relevant code of the test so I can try to replicate this?

**Comment by alessandrofama** [comment]
Please reopen if you've got more info here.
