### ISSUE TITLE
Unable to load addon script | identifier "Waapi" isn't declared in the current scope

### ISSUE THREAD

**Issue by MUTEDGALAXY** [alessandrofama/wwise-godot-integration#38]
Hello, basically, setup fails and it throws me 2 error messages:
![image](https://user-images.githubusercontent.com/53514993/133365003-f8e3ce04-ebe5-4084-84a1-e4005192880e.png)
![image](https://user-images.githubusercontent.com/53514993/133365017-9eea7aae-1482-4661-a8bf-2f5b1dc13c64.png)

waapi_picker.gd script error:
![image](https://user-images.githubusercontent.com/53514993/133365225-3b0770fe-b671-4381-b071-06da2658fd2e.png)

wwise_custom_nodes.gd error
![image](https://user-images.githubusercontent.com/53514993/133365263-b4207a6e-c4b7-4565-b154-630cd58c277d.png)

Here's the autoload tab:
![image](https://user-images.githubusercontent.com/53514993/133365303-170e211d-a768-49f5-8439-9a1fc4467a30.png)

Debugger Output:
![image](https://user-images.githubusercontent.com/53514993/133365448-8c5d01c0-8247-4112-b945-ee1a268a5d1d.png)

Godot project was closed during installation process.
Manual instalation gives me the same result.
I use Godot 3.3.3 (Not Mono)
OS is Windows 10

**Comment by alessandrofama** [comment]
Can you verify that you have the MSVC C++-x64/x86-Buildtools installed? You can find them as a package in the Visual Studio Installer. For example the MSVC v142 - VS 2019 C++ Build Tools. Installing these usually resolves the error.

**Comment by MUTEDGALAXY** [comment]
I installed build tools and it worked, thank you!
