### ISSUE TITLE
No lib file for ARM64 architecture

### ISSUE THREAD

**Issue by nicolasGab** [alessandrofama/wwise-godot-integration#43]
Hi, first of all, thanks a lot for the ongoing work to bring Wwise to Godot!  

I've started integrating the module in my team's workflow and it works great. We have a mix of different hardware and OS and have been able to get it working for Windows 10 and Intel MacOS but have run into trouble when trying to launch the project on an M1 chip MacOS device (M1 Mac mini).

The issue seems to be the compiled lib being available only for x86_64 architectures:

``` CONSOLE
Can't open dynamic library: [...]/wwise/bin/osx/debug/libWwiseGDNative.dylib, error: dlopen([...]/wwise/bin/osx/debug/libWwiseGDNative.dylib, 0x0002): 
tried: '[...]/wwise/bin/osx/debug/libWwiseGDNative.dylib' 
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), 
'/usr/lib/libWwiseGDNative.dylib' (no such file).
```   
  
  
Could you provide instructions as to how to compile the desired files for an ARM64 architecture or make them available on the repository? I would be happy to help testing the integration on Apple M1 devices.

**Comment by alessandrofama** [comment]
Which version of the integration & Wwise are you using?

I can look at this later or tomorrow, should be pretty easy to add support for an universal build that can target both architectures.

**Comment by nicolasGab** [comment]
We  are using  the latest release `1.4.0_Wwise2021.1.4.7707`

**Comment by alessandrofama** [comment]
Could you please try out these libs: [https://github.com/alessandrofama/wwise-godot-integration/suites/4695819916/artifacts/128283901](https://github.com/alessandrofama/wwise-godot-integration/suites/4695819916/artifacts/128283901)

They _should_ work both for x86_64 and arm64.

**Comment by francoisdlt** [comment]
Can confirm this works on my Mac Mini M1 running macOS 12.1 on Godot 3.4.1.stable with 1.4.0_Wwise2021.1.4.7707 (after allowing the unidentified developer in Security settings). Thanks !

**Comment by nicolasGab** [comment]
And it stills works on my intel Mac. Many thanks @alessandrofama!

**Comment by alessandrofama** [comment]
Nice! I'll merge my changes later and then will close this issue. Thanks for testing!
