### ISSUE TITLE
Fixed scripts for 3.4.2

### ISSUE THREAD

**Issue by aRsounds** [alessandrofama/wwise-godot-integration#48]
Hello Alessandro,

We had to change "preload" to "load" into wwise_custom_nodes.gd for it to work in the 3.4.2.
We are working on a mac.

Thanks for the great work

[wwise_godot_API_fixed_by_çois.zip](https://github.com/alessandrofama/wwise-godot-integration/files/8186908/wwise_godot_API_fixed_by_cois.zip)

**Comment by Amberlim** [comment]
thanks!

**Comment by alessandrofama** [comment]
Hi @aRsounds, I was not able to reproduce this on my intel mac & Godot 3.4.2 - If you happen to remember how to trigger this problem I can look at this again. I have found another unrelated bug in the installation process, so thanks anyway!
