### ISSUE TITLE
Playback Audio Session Category Setting Missing

### ISSUE THREAD

**Issue by jasonpkovalski** [alessandrofama/wwise-godot-integration#50]
On iOS, it would be useful to have the `Playback` option for the Audio Session Category under Wwise iOS Advanced Settings: https://github.com/alessandrofama/wwise-godot-integration/blob/main/wwise-gdnative/gdnative-demo/wwise/wwise_settings.gd#L128-L129.

The `AVAudioSessionCategoryPlayback` Audio Session Category will allow audio to play in silent mode without having to request audio input / microphone access (the only way to play audio in silent mode currently is to use the `Play and Record` category).
![Screen Shot 2022-04-05 at 9 00 10 PM](https://user-images.githubusercontent.com/12146670/161874899-2e208167-2bc3-4c2b-aea0-868533ea1843.png)

**Comment by alessandrofama** [comment]
Could you try adding a "playback" enum value to the settings snippet you provided, it should work out of the box on the cpp side:

```
	_add_setting(WWISE_IOS_ADVANCED_SETTINGS_PATH + "audio_session_category", 0,
				TYPE_INT, PROPERTY_HINT_ENUM, "Ambient, Solo Ambient, Play And Record, Playback")
```

Probably need to launch the scene once or restart the engine for the new value to appear in the settings.

**Comment by jasonpkovalski** [comment]
@alessandrofama Simply adding that enum value worked!  Should I close this issue or leave it open?

**Comment by alessandrofama** [comment]
I will close the issue as soon as I push the fix, thanks for reporting this!
