### ISSUE TITLE
Cant load /WwiseGDNative.dll, error: Error 126: The specified module could not be found

### ISSUE THREAD

**Issue by coobenguy** [alessandrofama/wwise-godot-integration#53]
First tried this in godot 3.4, then tried in 3.3.4 and got the exact same errors. Not sure what would be causing this and cant find any other reports about this issue.

**Comment by alessandrofama** [comment]
On Windows you need to install the MSVC C++-x64/x86-Buildtools. You can find them as a package in the Visual Studio Installer. For example the MSVC v142 - VS 2019 C++ Build Tools. Installing these usually resolves this error.

**Comment by coobenguy** [comment]
ahh alright thanks, nice work on this btw, if I can get this working in vr projects its gonna be the only reason I stay with godot! (The default sound system is garbage for vr enough that it alone made me want to go to unity)
