### ISSUE TITLE
godot::Wwise::loadBankID: AK_Fail ID 1355168291   <C++ Source>  D:\a\wwise-godot-integration\wwise-godot-integration\wwise-gdnative\src\wwise_gdnative.cpp:265 @ godot::Wwise::loadBankID()

### ISSUE THREAD

**Issue by coobenguy** [alessandrofama/wwise-godot-integration#54]
This is a weird one. 
1. I dont use a my D drive. Havent installed anything to it in years.
2. There is no folder "a"in the root of my D drive.
3. There is no root folder "a" in ANY of my drives. 

Everything wwise, godot, and C++ related are installed on my main C drive, so I really cant tell if this is an issue with the actual integration or if this is an issue just with my install?

**Comment by coobenguy** [comment]
oh alright (I guess its pretty obvious im very new to this haha) 

Im not sure how you could, because as far as I can tell I followed everything in your setup videos to a T. I set Init to load on startup in the "common wwise user settings" and I have disabled Use Soundbank names. My soundbanks and ID's were generated fine, they look just like yours did in the video. Ive also tried this in 3 separate new projects.

On a side note, I tried installing the newest 1.5 version and it has completely broken everything else, including when I try to go back to 1.4 so Im starting to think this is just not going to work for me

**Comment by alessandrofama** [comment]
If you could try with the 1.5 now, there was a small prob with the Windows libs I've fixed right at this moment.
With the new version ,some of the installation and IDs generation workflow changed, so sadly the videos are not up-to-date anymore, but they should still give a good general idea of the workflow. 

The most updated guide is this so far: https://github.com/alessandrofama/wwise-godot-integration/wiki/Getting-Started

You can send me your project if you like, so I can take a quick look. It should fine the Init bank fine, but there is clearly something going wrong^^

**Comment by coobenguy** [comment]
yeah Id really appropriate it here's the project file

https://drive.google.com/file/d/1lsB0PrOOu-z7KM9tNX-WSOvbG-fHae-o/view?usp=sharing

if I can actually get this figured out and integrate it into a VR project I was gonna make at least a basic tutorial myself. VR Godot devs have been starved of decent audio and it seems as though not many people have come across this as a solution before

**Comment by alessandrofama** [comment]
<img width="680" alt="Screenshot 2022-04-28 at 08 54 27" src="https://user-images.githubusercontent.com/26153311/165697594-c0045c61-1f41-46b6-b9d5-d703ae60dff5.png">
This is the wrong path. Your banks are in res://wwise/GeneratedSoundBanks

**Comment by coobenguy** [comment]
Oh wow alright thanks for your help again, I wonder why addons was the default path for it haha
