### ISSUE TITLE
Script does not inherit a Node when adding waapi-gdnative.gdns as an auto-load

### ISSUE THREAD

**Issue by eruhlinteractive** [alessandrofama/wwise-godot-integration#56]
![image](https://user-images.githubusercontent.com/45072333/179103839-cede24c7-8101-4e43-94f3-ef301c1dea40.png)

When adding the `res://addons/wwise/bin/waapi-gdnative.gdns` as an auto-load script (automatically added while following the [getting started guide](https://github.com/alessandrofama/wwise-godot-integration/wiki/Getting-Started)), Godot produces an error that the script could not be loaded because it does not inherit a Node.

Godot Version: 3.4 Stable

**Comment by alessandrofama** [comment]
What OS are you using? Any other errors in the console? Haven't been able to reproduce the error on Windows and macOS. This error should occur when godot fails to load the Waapi lib. Does it also happen with wwise-gdnative.gdns?

**Comment by eruhlinteractive** [comment]
I was using Windows 10 when the error occurred, and the `wwise-gdnative.gdns` didn't seem to produce the same error.

However, I was able to resolve the issue by removing and reinstalling the Wwise authoring console version 2021.1.4.7707.

**Comment by Maaack** [comment]
I'm also experiencing this issue on Linux every time I open Godot. A collaborator has the Wwise authoring console, I do not. However, the integration seems to work, despite the error. I have the library for my platform, as well as for Mac and Windows.
![Screenshot from 2022-07-29 12-30-01](https://user-images.githubusercontent.com/788630/181831143-edfb760f-4c3a-4098-bc12-0f42e7ba9cad.png)

**Comment by alessandrofama** [comment]
This is unfortunate, but to be expected on Linux. There is no Wwise authoring application for this platform, so it did not make sense to include a Waapi library for Linux (Waapi enables communication with the authoring application). 

Is `waapi-gdnative.gdns` present in your autoload list in the project settings? If so, remove it from there and the error should disappear. It may be that it will be added back by your collaborators if you use version control.

This has no effect on the Wwise sound engine, but is still annoying when an error pops up in the console. Perhaps there is a way to prevent this.

**Comment by Maaack** [comment]
Okay, it's more annoying than causing any problems. Thanks for the suggestions.

**Comment by alessandrofama** [comment]
What OS are you using? Any other errors in the console? Haven't been able to reproduce the error on Windows and macOS. This error should occur when godot fails to load the Waapi lib. Does it also happen with wwise-gdnative.gdns?Am 15.07.2022 00:58 schrieb Ethan Ruhl ***@***.***>:

When adding the res://addons/wwise/bin/waapi-gdnative.gdns as an auto-load script (automatically added while following the getting started guide), Godot produces an error that the script could not be loaded because it does not inherit a Node.
Godot Version: 3.4 Stable
