### ISSUE TITLE
Stuck with AK_Fail ID error

### ISSUE THREAD

**Issue by Nomys** [alessandrofama/wwise-godot-integration#57]
My soundbank won't load properly.

- I'm on wwise 2021.1.4 (build 7077) and I have use the integration tool with the same setting.
- Godot 3.4 stable
- I have deselected the "Use SoundBank Names" checkbox on Wwise
- I export soundbanks and Soundbank Headers in my-godot-project/wwise/GeneratedSoundbank folder
- I used the waapi clicker to generate wwise ids in godot
- I created a AK_Bank with my soundbank with enter_tree loading setup
- I have an AK_Listener
- I have an AK_Event with my event on ready setup.

If i'm understanding this correctly when I generate my soundbanks I have to restart Godot and regen wwise ids with the waapi clicker. I did all this and I'm still stuck with AK_Fail ID error and the AK_Event identifier error.

edit: I tried all this on 2 projects, my current work and an empty one.

**Comment by alessandrofama** [comment]
> I created a AK_Bank with my soundbank with enter_tree loading setup 

Do you load the `Init` bank at all? This is required before loading any other bank.

**Comment by Nomys** [comment]
I wasn't but after adding the Init bank (into an AK_Bank node) I just have one more AK_Fail ID error.

**Comment by alessandrofama** [comment]
This error usually means it can't locate the banks on disk. I would check if the `base path` to the platform banks is correct in the project settings:

![image](https://user-images.githubusercontent.com/26153311/179506711-64b4d670-8a7b-4b83-8416-462c4979645f.png)

If it is then something else is going wrong. Could you send me your empty project so I can take a quick look at it?

**Comment by alessandrofama** [comment]
Ah I see the problem, you have exported all your banks into the `GeneratedSoundBanks` folder, but the banks need to be in extra subfolder named after your Wwise platform. So move them into `GeneratedSoundBanks\Windows` if you are using Windows. These are the paths:
![image](https://user-images.githubusercontent.com/26153311/179553837-86438308-3490-49f2-9dd5-f8656c4c631a.png)
 (missing \Linux).

**Comment by Nomys** [comment]
Wow thanks I didn't know that matter!
I will test this tomorrow and get back to you!

**Comment by Nomys** [comment]
It's working! 
Thanks, it was very much a wwise problem than a wwise-godot problem ;o)
