### ISSUE TITLE
Godot 4 ?

### ISSUE THREAD

**Issue by Noiros** [alessandrofama/wwise-godot-integration#58]
A simple question, I have been working for a long time on a game on godot 4 and I would like to use wwise in this project, so I was wondering if you were going to upgrade to 4.0?

**Comment by alessandrofama** [comment]
Yes, but not before the late beta phase. GDExtension, the successor to GDNative, is not yet stable enough to port this integration.

**Comment by Noiros** [comment]
ok, thank you !
