### ISSUE TITLE
Godot 3.5 support

### ISSUE THREAD

**Issue by btzr-io** [alessandrofama/wwise-godot-integration#61]
Is this plugin working on 3.5 ?

I can't load any soundbank. I have follow the guide and read the wiki, everything looks fine:

![image](https://user-images.githubusercontent.com/14793624/185542765-91d93e2d-93a5-4310-83e8-aa86323dd2d8.png)

Until I try to load the soundbank on the AKBank node:

![image](https://user-images.githubusercontent.com/14793624/185543284-245030cb-9d7c-42b3-9fd6-5c87635e43cb.png)

> Note: The ID generation seems to also work fine.

 I have tried this solution but it doesn't work either:
https://github.com/alessandrofama/wwise-godot-integration/issues/12#issuecomment-735392008
https://github.com/alessandrofama/wwise-godot-integration/issues/57#issuecomment-1187683563

Or maybe a direct issue with my Wwise current version ?

> At the moment, Wwise version 2021.1.4.7707 is supported

Godot 3.5
Wwise 2021.1.10.7883
Wwise Godot integration 1.5.0

**Comment by alessandrofama** [comment]
Godot 3.5 works fine.
Your version of Wwise should work fine as it's only a minor version upgrade.
Have you loaded the Init bank before trying to load any other bank? If yes and the issue still persists send me a reproduction project so I can take a look at it

**Comment by btzr-io** [comment]
> Have you loaded the Init bank before trying to load any other bank

Thanks, I did try to load the init bank but I can't remember if I load it first. I'll try again and post the reproducible example if the error persists.

**Comment by btzr-io** [comment]
> Godot 3.5 works fine. Your version of Wwise should work fine as it's only a minor version upgrade. Have you loaded the Init bank before trying to load any other bank? If yes and the issue still persists send me a reproduction project so I can take a look at it

I can't believe that was it. I'll close this now. Is there any docs regarding this solution ?

**Comment by alessandrofama** [comment]
If you have used Wwise in the past, it is almost common knowledge that the Init bank must be loaded first. However, I have added the information to the description of the AkBank node because it might be useful for new users.

**Comment by btzr-io** [comment]
> If you have used Wwise in the past, it is almost common knowledge that the Init bank must be loaded first. However, I have added the information to the description of the AkBank node because it might be useful for new users.

Indeed, it was my first time working with wwise and I was just setting up the project for another dev. I'll keep this in mind next time.  👍
