### ISSUE TITLE
Official support for Wwise version 2021.1.5.7749 or higher

### ISSUE THREAD

**Issue by nicolasGab** [alessandrofama/wwise-godot-integration#62]
Wwise version **2021.1.5.7749** fixes a major issue for MacOS version **12.3** and up, where the Wwise app crashes on startup. This is *"caused by the removal of the Python framework starting with macOS 12.3"* as mentioned in [this post](https://www.audiokinetic.com/qa/10015/wwise-doesnt-open-on-m1-mac) on the AudioKinetic website.

Has anyone tested the compatibility of the Godot integration with newer minor versions of the Wwise app?

**Comment by alessandrofama** [comment]
Soundbanks generated with a higher minor version of the Wwise authoring app should work with this integration according to the docs: https://www.audiokinetic.com/library/edge/?source=Help&id=soundbank_backward_compatibility

**Comment by nicolasGab** [comment]
I can confirm bumping minor versions works fine as is, thank you for the link to the docs. 
Would it be worth mentioning in the integration's documentation for other MacOS users?

**Comment by alessandrofama** [comment]
I've added the info here: https://github.com/alessandrofama/wwise-godot-integration/wiki/Wwise-version-upgrade
