### ISSUE TITLE
Do Audio files need to be within the project?

### ISSUE THREAD

**Issue by ha-kuro** [alessandrofama/wwise-godot-integration#64]
Was just curious if we needed to keep all the .wav files within the Godot projects filesystem or if Wwise imports these when generating soundbanks

**Comment by alessandrofama** [comment]
Wwise puts all the audio data for your game into banks. See https://www.audiokinetic.com/library/edge/?source=WwiseFundamentalApproach&id=understanding_soundbanks_understanding_soundbanks

And https://www.audiokinetic.com/courses/wwise101/?source=wwise101&id=adding_an_event_to_soundbank
