### ISSUE TITLE
Error integrating Wwise - AK_InvalidID

### ISSUE THREAD

**Issue by ha-kuro** [alessandrofama/wwise-godot-integration#65]
Found an error while integrating Wwise with Godot for Ludum Dare 51 (tomorrow) - 

![image](https://user-images.githubusercontent.com/107250857/193181734-49eeb38e-bf20-477a-a3f8-9c7896d1045d.png)
![image](https://user-images.githubusercontent.com/107250857/193183097-44376097-c0ef-48a1-835b-76016484250a.png)

### Steps taken:
1. Integrate Wwise with 1.5.0 Integration.App.win64.exe
2. Enable Wwise in plugins tab
3. Generate Soundbanks with Header file directed at wwise/GeneratedSoundBanks
4. Add AKEvent node and set Event, with Trigger On set to Ready
5. Launch the scene

All events are visible in the Waapi Picker, and in the AKEvent node's Event property.

I've tried loading the Init bank using Wwise common-user-settings (in Godot's Project Settings), but receiving a new invalid ID error in the debugger:
![image](https://user-images.githubusercontent.com/107250857/193183907-786c879d-080a-4cf8-a7f4-827b1a16cbc5.png)

Our team would love to use this integration since our music/sound producer is familiar with Wwise.
Also wanted to say fantastic work with the integration and it's great to see Godot on Wwise's [home page](https://www.audiokinetic.com/en/products/wwise/).

**Comment by alessandrofama** [comment]
Ak_Fail when loading the bank almost always means it didn't find the bank.

Have you already checked the other closed issues regarding this problem? 

https://github.com/alessandrofama/wwise-godot-integration/issues/57
https://github.com/alessandrofama/wwise-godot-integration/issues/54
https://github.com/alessandrofama/wwise-godot-integration/issues/12#issuecomment-735392008

Followed the wiki? https://github.com/alessandrofama/wwise-godot-integration/wiki/Getting-Started

If this doesn't solve your problem send me your project and I will take a look at it.

**Comment by alessandrofama** [comment]
No follow up comment, I guess this was a configuration error.

**Comment by ha-kuro** [comment]
> No follow up comment, I guess this was a configuration error.

Apologies, we didn't end up fixing the error in time for the Game Jam and decided to use Godot's native audio system.
I've looked through the previous issues #57 #54 #12 and couldn't find a solution that would work for our issue.
Thanks very much for responding quickly
