### ISSUE TITLE
Does this integration work with any other version of Wwise?

### ISSUE THREAD

**Issue by Dakkers** [alessandrofama/wwise-godot-integration#66]
For some reason I'm unable to install Wwise 2021.1.4.7707 😭 Is it possible for me to use a different version?

**Comment by alessandrofama** [comment]
Using a different minor version of a major Wwise release works out of the box and SoundBanks will be backwards compatible. See: https://www.audiokinetic.com/library/edge/?source=Help&id=soundbank_backward_compatibility

So 2021.1.5 will work for example.
