### ISSUE TITLE
No audio when exporting to HTML

### ISSUE THREAD

**Issue by HeartBox12** [alessandrofama/wwise-godot-integration#69]
I've made sure to include all the file types in the exporting settings ahead of time, and I've ensured that the same audio works on other export types. I'm not going to assume that HTML exports are not supported at all when I haven't seen anything stating that explicitly, so I'm going to check here and see if anyone has a solution.

**Comment by alessandrofama** [comment]
Yeah sorry, Wwise doesn't support HTML exports at all. If anything changes in that regard we will try to add support too :)
