### ISSUE TITLE
Event ID not found

### ISSUE THREAD

**Issue by snadon** [alessandrofama/wwise-godot-integration#70]
Hi, I'm trying to trigger an event but it just won't work.

If I right click the event in the Waapi Picker and select `Play` it does play the music. Is there something I'm missing?

I also tried with the nodes instead of programmatically but it throws the same error.

```
extends Spatial

# Called when the node enters the scene tree for the first time.
func _ready():
	Wwise.load_bank_id(AK.BANKS.INIT)
	Wwise.load_bank_id(AK.BANKS.MUSIC)	
	Wwise.register_game_obj(self, self.get_name())
	Wwise.register_listener(self)
	Wwise.set_3d_position(self, self.get_global_transform())
	
	var result = Wwise.post_event_id(AK.EVENTS.PLAY, self)
	print(result)
```

```
class_name AK

class EVENTS:

	const PLAY = 1256202815 
	const STOP = 788884573 

	const _dict = { 
	 "PLAY": PLAY,
	 "STOP": STOP
	} 

class STATES:

	class SPEED:
		const GROUP = 640949982 

		class STATE:
			const NONE = 748895195 
			const WALK = 2108779966 
			const RUN = 712161704 

	class ZONE:
		const GROUP = 832057375 

		class STATE:
			const NONE = 748895195 
			const ZONE_A = 2643994039 
			const ZONE_B = 2643994036 

	const _dict = { 
		"SPEED": {
			"GROUP": 640949982,
			"STATE": {
				"NONE": 748895195,
				"WALK": 2108779966,
				"RUN": 712161704,
			} 
		}, 
		"ZONE": {
			"GROUP": 832057375,
			"STATE": {
				"NONE": 748895195,
				"ZONE_A": 2643994039,
				"ZONE_B": 2643994036
			} 
		} 
	} 

class SWITCHES:

	const _dict = {} 

class GAME_PARAMETERS:

	const _dict = {} 

class TRIGGERS:

	const _dict = {} 

class BANKS:

	const INIT = 1355168291 
	const MUSIC = 3991942870 

	const _dict = { 
	 "INIT": INIT,
	 "MUSIC": MUSIC
	} 

class BUSSES:

	const MASTER_AUDIO_BUS = 3803692087 

	const _dict = { 
	 "MASTER AUDIO BUS": MASTER_AUDIO_BUS
	} 

class AUX_BUSSES:

	const _dict = {} 

class AUDIO_DEVICES:

	const SYSTEM = 3859886410 
	const NO_OUTPUT = 2317455096 

	const _dict = { 
	 "SYSTEM": SYSTEM,
	 "NO OUTPUT": NO_OUTPUT
	} 

class EXTERNAL_SOURCES:

	const _dict = {} 
```

<img width="148" alt="Screenshot 2023-01-10 at 11 27 14 AM" src="https://user-images.githubusercontent.com/539572/211607186-7855bdd2-90c3-4a8a-b96c-ffe3a17cca59.png">
<img width="319" alt="Screenshot 2023-01-10 at 11 28 19 AM" src="https://user-images.githubusercontent.com/539572/211607399-a2992148-3139-4e08-933f-09edca88aad2.png">

**Comment by snadon** [comment]
Yes the banks are loading fine. I mailed you the test project I did especially for this issue.

**Comment by alessandrofama** [comment]
Your music bank looks very small (1kb), and if I look at Wwise_IDs.h I can't see the events in there. Are you sure you included them in the bank? Maybe you need to rebuild the soundbanks?

**Comment by snadon** [comment]
I followed the instructions to export everything. I suppose the problem lies with my exportation then, I'll try to get the missing data and get back to you. Thank you!

**Comment by snadon** [comment]
It's working perfectly now! I had to drag the interactive music hierarchy for the sound bank.

<img width="958" alt="Screenshot 2023-01-10 at 2 08 26 PM" src="https://user-images.githubusercontent.com/539572/211640032-4b26b34e-b4c2-4693-961d-56db6408640e.png">
