### ISSUE TITLE
Godot 4.x Support

### ISSUE THREAD

**Issue by EPOCHvoyager** [alessandrofama/wwise-godot-integration#72]
As GDNative is now dead - are there plans for this to live on as a GDExtension?

**Comment by alessandrofama** [comment]
Hi,

thank you for your interest in the Wwise plugin. I'm aware of the discontinuation of GDNative and the introduction of GDExtension.

Regarding your question, I'm currently focusing on finishing up my FMOD plugin, but I do plan to update the Wwise integration to support GDExtension in the near future. However, I can't provide an exact timeframe for when that will happen. It may take 1-2 months, but I can't promise anything at this point.

Thank you for your patience and understanding. If you have any further questions or concerns, please don't hesitate to let me know.

**Comment by EPOCHvoyager** [comment]
Glad to hear it! Take your time, man.

**Comment by demee3** [comment]
oh yes mate, looking forward to it

**Comment by smks** [comment]
Look forward to it too ☺️ I'll need Wwise to be able to upgrade to Godot 4.0
