### ISSUE TITLE
Wiki: suggestions for the `Building the GDExtension Library` page

### ISSUE THREAD

**Issue by nicolasGab** [alessandrofama/wwise-godot-integration#74]
Hi! I'm currently in the process of building the library and I would like to suggest a few additions to the `Building the GDExtension Library` wiki page to make it simpler for anyone who needs to do this as well. These are the steps I followed, which if they are correct, could be added to the top of the wiki page:

# Download and install SCons build tool
## MacOS
- With Homebrew
`brew install scons`
## Windows
- Check for a Python installation on your machine
`python --version`
- If python is not installed, head over to the Python website to download it
- In the Python install wizard, make sure to install `pip` as well
- Then you can install SCons with `pip`
`pip install SCons`

# Clone the `wwise-godot-integration` repository
- Clone the repository
`git clone git@github.com:alessandrofama/wwise-godot-integration.git`
- Initialize and fetch the repository's submodules
`git submodule update --init --recursive`
`git submodule update --recursive --remote`
- Checkout the `tag` with the version you want to build, for example
`git checkout tags/2.0.0-Wwise2022.1-Godot4.0.4`

From there you can follow the general build instructions

**Comment by alessandrofama** [comment]
Added, thanks!
