### ISSUE TITLE
InvalidID error while posting events [Godot 4.2, wwise 2023.1]

### ISSUE THREAD

**Issue by Voyager0001** [alessandrofama/wwise-godot-integration#92]
### Wwise integration version

wwise-2023.1-for-godot-4.2-stable-2.0.4

### System information

Windows 11

### Issue description

![image](https://github.com/alessandrofama/wwise-godot-integration/assets/83073365/46846325-6a5d-4548-9479-26173e2268f3)
Posting events and getting rtpc's doesn't work 

### Steps to reproduce

In wwise authoring: make event, make rtpc
generate soundbank in the GeneratedSoundBanks/WIndows folder

in godot:
generate wwise ids
load bank asyncly
register game object
register listener
post event
get rtpc

### Minimal reproduction project

godot:
[car.zip](https://github.com/alessandrofama/wwise-godot-integration/files/13687236/car.zip)
wwise project if needed:
[new.zip](https://github.com/alessandrofama/wwise-godot-integration/files/13687262/new.zip)

**Comment by alessandrofama** [comment]
1) You are trying to post an Event but have only tried to load the Init bank. This will not contain Events. See: https://www.audiokinetic.com/en/library/edge/?source=SDK&id=concept_banks.html 
You will have to create another Soundbank, add your `go` Event to it and load it after the Init bank.

2) You are trying to a Soundbank by usin the `*_id` function of the Wwise singleton. This is only supported if you 1) Disable the `Use SoundBnk Names for Filenames` setting in the Project Settings of the Wwise Authoring application. 2) Disable the `Use SoundBank names` setting in the Wwise setting withing Godot (-> Project Settings-Toggle Advanced settings-Wwise). This is described here in the wiki: https://github.com/alessandrofama/wwise-godot-integration/wiki/Loading-Soundbanks

After doing this it should work fine. Is it enough info or do you need more help?

**Comment by Voyager0001** [comment]
It works just fine! It's exactly as you said. I think my error was starting to learn wwise in godot first and as such there's just no detailed tutorials available for newbies. Thank you so much for taking the time!
